spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #스프링 restart와 관계 없이 DB에 데이터를 남겨놓고 테스트를 진행할 경우, 즉 commit 발생
#      ddl-auto: none
      #스프링 restart 되면 DB 데이터는 모두 롤백되어 초기화, 즉, 테스트 시에만 데이터 추가되었다가 모두 rollbak 처리됨 commit 하지 않음
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    #OSIV 이 기능이 true 이면, 화면에 View 로딩이 완료되는 시점까지 DB 커넥션이 반환되지 않는다.
    #만약, 이 기능이 false 이면, @Transactional 로 진행되는 부분의 작업이 종료됨과 동시에 DB 커넥션이 반환된다.
    #DB 커넥션 반환 시점에 따라 JPA 영속성이 Controller 까지 적용 가능하냐 아니면 Service 와 Repository 까지만 적용되냐의 차이가 발생한다.
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace